sudo docker build -t 'lab1' LAB1
sudo docker build -t 'lab2' LAB2
sudo docker build -t 'lab3' LAB3
sudo docker build -t 'lab4' LAB4
sudo docker build -t 'lab5' LAB5
sudo docker build -t 'chal1' CHAL1
sudo docker build -t 'chal2' CHAL2
sudo docker build -t 'chal3' CHAL3
sudo docker build -t 'chal4' CHAL4
sudo docker build -t 'chal5' CHAL5
sudo docker build -t 'chal6' CHAL6
sudo docker build -t 'chal7' CHAL7
sudo docker build -t 'chal8' CHAL8
sudo docker build -t 'chal9' CHAL9
sudo docker build -t 'chal12' CHAL12
sudo docker build -t 'chal13' CHAL13
sudo docker build -t 'chal14' CHAL14
sudo docker build -t 'chal16' CHAL16
