DROP TABLE IF EXISTS `tHeM30WINGK1TTI3S`;

CREATE TABLE `tHeM30WINGK1TTI3S` (
  `C4TNaM4E` varchar(40) DEFAULT NULL,
  `FLAG` varchar(40) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


LOCK TABLES `tHeM30WINGK1TTI3S` WRITE;
INSERT INTO `tHeM30WINGK1TTI3S` VALUES ('4NYTH1NG_BUT_4RV1N','flag{BlN4RY_C4T5_S3ARCH:)}');
UNLOCK TABLES;
